name: flutter_html_math
description: Math widget for flutter_html.
version: 3.0.0-alpha.3
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html: '>=3.0.0-alpha.3 <4.0.0'
#  flutter_html:
#    path: ../..

  flutter_math_fork: '>=0.6.2 <1.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
